config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root :to => "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	has_one_attached :book_image

	validates :book_image, presence: true
	validates :title, presence: true
  	validates :body, presence: true, length: { maximum: 200 }

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	def get_book_image
		unless book_image.attached?
		  file_path = Rails.root.join('app/assets/images/no_book.png')
		  book_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/png')
		end
		book_image
	  end
	
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body,:book_image)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/views/books/_comment.html.erb
<% book.book_comments.each do |book_comment| %>
	<div class="card mb-3">
        <div class="card-body">
        	<div class="card-text">         
            	<%= link_to user_path(@book.user) do %>
                	<%= image_tag book_comment.user.get_profile_image, class: "profile-image-sm rounded-circle" %>
            	<% end %>
                <small class="text-muted">
                <%= book_comment.created_at.strftime("%Y/%m/%d %X") %></small>
            </div>
            <p class="card-text"><%= simple_format(book_comment.comment)  %></p>
	    	<% if current_user == book_comment.user %>
				<div class="card-text text-right">
					<%= link_to book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete,  data: { confirm: "削除してもよろしいですか？" }  do %>
						<i class="fas fa-trash-alt"></i>
					<% end %>
				</div>
			<% end %>
        </div>
    </div>
<% end %>

コメント:
<%= form_with model:[@book,@book_comment], local: true do |f| %>
  <%= f.text_area :comment, class:"form-control" %><br>
  <%= f.submit '送信', class:"btn btn-sm btn-success" %>
<% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :book_image %>
    <%= f.file_field :book_image, class: '' %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<% books.each do |book| %>
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-4">
        <%= image_tag book.get_book_image, class:"book-image-xl card-img-top"%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <div class="card-text text-right">         
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image, class: "profile-image-sm rounded-circle" %>
          <% end %>
          <small class="text-muted">
          <%= book.created_at.strftime("%Y/%m/%d %X") %></small>
        </div>
        <h5 class="card-title"><%= book.title%></h5>
        <p class="card-text"><%= book.body %></p>
        <div class="card-text text-right">
          <%= render "favorites/favorite-btn", book: book %>
          <i class="fas fa-comment"></i><%= book.book_comments.count %>
        </div>
        <div class="card-text text-right">
            <%= link_to book_path(book), class: "book_#{book.id}" do %>
              詳細へ
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/books/_index_all.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Opinion</th>
      <th>favorite</th>
      <th>comment</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td >
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image, class: "profile-image-sm rounded-circle" %>
          <% end %>
        </td>
        <td >
          <%= link_to book_path(book), class: "book_#{book.id}" do %>
            <%= image_tag book.get_book_image, class: "book-image-sm" %>
            <%= book.title.truncate(12)%>
          <% end %>
        </td>
        <td >
          <%= book.body.truncate(12) %>
        </td>
        <td >
          <%= render "favorites/favorite-btn", book: book %>
        </td>
        <td >
          <i class="fas fa-comment"></i><%= book.book_comments.count %>
        </td>
        <td >
          <%= book.created_at.strftime("%Y/%m/%d") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- table table-responsive -->
<div class="table-responsive">
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Opinion</th>
      <th>favorite</th>
      <th>comment</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td nowrap>
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image, class: "profile-image-sm rounded-circle" %>
          <% end %>
        </td>
        <td nowrap>
          <%= link_to book_path(book), class: "book_#{book.id}" do %>
            <%= image_tag book.get_book_image, class: "book-image-sm" %>
            <%= book.title.truncate(12)%>
          <% end %>
        </td>
        <td nowrap>
          <%= book.body.truncate(12) %>
        </td>
        <td nowrap>
          <%= render "favorites/favorite-btn", book: book %>
        </td>
        <td nowrap>
          <i class="fas fa-comment"></i><%= book.book_comments.count %>
        </td>
        <td nowrap>
          <%= book.created_at.strftime("%Y/%m/%d") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<!-- table レイアウト目的 -->

<!--
<table class='table table-hover table-inverse'>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to book_path(book), class: "book_#{book.id}" do %>
            <%= image_tag book.get_book_image, class: "book-image-lg" %>
          <% end %>
        </td>
        <td>
          <div class="text-right">
            <%= link_to user_path(book.user) do %>
              <%= image_tag book.user.get_profile_image, class: "profile-image-sm rounded-circle" %>
            <% end %>
            <small class="text-muted"><%= book.created_at.strftime("%Y/%m/%d %X") %></small>
          </div>
          </div>
          <h5><%= book.title%></h5>
          <p><%= book.body %><p>
          <div class="text-right">
            <%= render "favorites/favorite-btn", book: book %>
            <i class="fas fa-comment"></i><%= book.book_comments.count %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



-->

<!-- カード横 --->
<!--
<% books.each do |book| %>
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-4">
        <%= image_tag book.get_book_image, class:"card-img-top"%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <div class="card-text text-right">         
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image, class: "profile-image-sm rounded-circle" %>
          <% end %>
          <small class="text-muted">
          <%= book.created_at.strftime("%Y/%m/%d %X") %></small>
        </div>
        <h5 class="card-title"><%= book.title%></h5>
        <p class="card-text"><%= book.body %></p>
        <div class="card-text text-right">
          <%= render "favorites/favorite-btn", book: book %>
          <i class="fas fa-comment"></i><%= book.book_comments.count %>
        </div>
        <div class="card-text text-right">
            <%= link_to book_path(book), class: "book_#{book.id}" do %>
              詳細へ
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
-->
<!-- カード縦 --->
<!--
<div class="row">
  <% books.each do |book| %>
    <div class="col-md-6 col-lg-4 mb-3">
      <div class="card">
        <%= image_tag book.get_book_image, class:"card-img-top"%>
        <div class="card-body text-right">
            <%= link_to book_path(book), class: "book_#{book.id}" do %>
              詳細へ
            <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= book.title.truncate(12)%></h5>
          <p class="card-text"><%= book.body.truncate(30) %></p>
        </div>
        <div class="card-body text-right">
          <%= render "favorites/favorite-btn", book: book %>
          <i class="fas fa-comment"></i><%= book.book_comments.count %>
        </div>
        <div class="card-body text-right">
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image, class: "profile-image-sm rounded-circle" %>
          <% end %>
          <%= book.created_at.strftime("%Y/%m/%d") %>
        </div>
      </div>
    </div>
  <% end %>
</div>
-->

app/views/books/_index_table.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Opinion</th>
      <th>favorite</th>
      <th>comment</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image, class: "profile-image-sm rounded-circle" %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book), class: "book_#{book.id}" do %>
            <%= image_tag book.get_book_image, class: "book-image-sm" %>
            <%= book.title.truncate(12)%>
          <% end %>
        </td>
        <td>
          <%= book.body.truncate(12) %>
        </td>
        <td>
          <%= render "favorites/favorite-btn", book: book %>
        </td>
        <td>
          <i class="fas fa-comment"></i><%= book.book_comments.count %>
        </td>
        <td>
          <%= book.created_at.strftime("%Y/%m/%d") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_index_table_layout.html.erb
<table class='table table-hover table-inverse'>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to book_path(book), class: "book_#{book.id}" do %>
            <%= image_tag book.get_book_image, class: "book-image-lg" %>
          <% end %>
        </td>
        <td>
          <div class="text-right">
            <%= link_to user_path(book.user) do %>
              <%= image_tag book.user.get_profile_image, class: "profile-image-sm rounded-circle" %>
            <% end %>
            <small class="text-muted"><%= book.created_at.strftime("%Y/%m/%d %X") %></small>
          </div>
          </div>
          <h5><%= book.title%></h5>
          <p><%= book.body %><p>
          <div class="text-right">
            <%= render "favorites/favorite-btn", book: book %>
            <i class="fas fa-comment"></i><%= book.book_comments.count %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
      <div class="card mb-3">
        <div class="row no-gutters">
          <div class="col-md-4">
            <%= image_tag @book.get_book_image, class:"card-img-top"%>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <div class="card-text text-right">         
                <%= link_to user_path(@book.user) do %>
                  <%= image_tag @book.user.get_profile_image, class: "profile-image-sm rounded-circle" %>
                <% end %>
                <small class="text-muted">
                <%= @book.created_at.strftime("%Y/%m/%d %X") %></small>
              </div>
              <h5 class="card-title"><%= @book.title%></h5>
              <p class="card-text"><%= @book.body %></p>
              <div class="card-text text-right">
                <%= render "favorites/favorite-btn", book: @book %>
                <i class="fas fa-comment"></i><%= @book.book_comments.count %>
              </div>
              <% if current_user == @book.user %>
                <div class="card-text text-right">
        					<%= link_to edit_book_path(@book.id) do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
        					<%= link_to book_path(@book.id), method: :delete, data: { confirm: "削除してもよろしいですか？" } do %>
				        		<i class="fas fa-trash-alt"></i>
					        <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <%= render 'books/comment', book: @book,book_comment: @book_comment%>
    </div>
  </div>
</div>